info:
  name: 6.2.2-LogCleanupSettings✅
  type: http
  seq: 2

http:
  method: POST
  url: "{{dev_url}}/ApplicationSettings/applicationsettings/log-cleanup-settings"
  body:
    type: json
    data: "{\r\n    \"AppKey\":\"\"\r\n}"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
